### ISSUE TITLE
How to move the generated doc to a subpath?

### ISSUE THREAD

**Issue by hufan-akari** [ionic-team/stencil-site#100]
I'm trying to translate the documents and to deploy it on Github Pages.
But the generated files and the request in the script are based on the root of domain. 

How to move it into a sub path? ( such as `username.github.io/stencil-site`)

I changed every path in source code which start with `/` to `/stencil-site/` and modified the config files as below:

stencil.config.js:
```js
exports.config = {
  bundles: [
    { components: ['stencil-site', 'site-header', 'landing-page', 'lazy-iframe', 'site-menu'] },
    { components: ['app-marked', 'document-component'] },
    { components: ['demos-page'] },
    { components: ['resources-page'] },
    { components: ['pwas-page'] }
  ],
  collections: [{ name: '@stencil/router' }],
  wwwDir: 'www/stencil-site',
  publicPatg: '/stencil-site/build'
};

exports.devServer = {
  root: 'www',
  watchGlob: '**/**'
};
```
gulpfile.js:
```js
var gulp = require('gulp');
var markdown = require('gulp-markdown');
var hljs = require('highlight.js');
gulp.task('default', function() {
  return gulp
    .src('./docs-md/**/*.md')
    .pipe(
      markdown({
        highlight: function(code) {
          return hljs.highlightAuto(code).value;
        }
      })
    )
    .pipe(gulp.dest('./www/stencil-site/docs-content'));
});
```

It works well under development mode.
But the prerender result is wrong.
![screen shot 2017-12-03 at 2 16 32 pm](https://user-images.githubusercontent.com/7829098/33522965-1bc3ab60-d835-11e7-855e-c78ebef5958a.png)

It rendered another stencil-site folder in the stencil-site.
How to correct it?

Or, what is the correct way to move the generated documents to a subpath?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. As the original underlying issue was resolved in the latest release I am going to close this issue for now.
