### ISSUE TITLE
The slack link is no longer active

### ISSUE THREAD

**Issue by cramhead** [ionic-team/stencil-site#101]
After clicking the slack link on the Contributors.md page slack reports that the "Invite link is no longer active". The link is currently https://join.slack.com/t/stencil-worldwide/shared_invite/enQtMjQ2MzkyMTY0MTk0LTQ4ODgzYjFjNjdkNDY3YWVhMmNlMTljMWQxNTM3Yjg0ZTIyZTM1MmU2YWE5YzNjNzE1MmQ3ZTk2NjQ1YzM5ZDM. 
The src/components/site-menu/site-menu.tsx is using the same link.
Should it be remove or updated?

**Comment by jgw96** [comment]
Hello! This has been fixed in the latest deploy of the site. Thanks!
