### ISSUE TITLE
Doc v3 : componentDidUnload missing

### ISSUE THREAD

**Issue by deleonio** [ionic-team/stencil-site#1012]
https://stenciljs.com/docs/component-lifecycle

**Comment by deleonio** [comment]
Was removed in v2. Is there no distroy hook?!

**Comment by rwaskiewicz** [comment]
Hey @deleonio 👋 

`componentDidUnload` was indeed removed in Stencil v2.0.0. The previous maintainers had made a note of this in the [Stencil Repo's `BREAKING_CHANGES.md` document](https://github.com/ionic-team/stencil/blob/main/BREAKING_CHANGES.md#use-disconnectedcallback-instead-of-componentdidunload). `disconnectedCallback` is the preferred way of checking for disconnection:

> Use disconnectedCallback() instead of componentDidUnload()
>
> - componentDidUnload: use disconnectedCallback instead of componentDidUnload ([4e45862](https://github.com/ionic-team/stencil/commit/4e45862f73609599a7195fcf5c93d9fb39492154))
>
> When Stencil is used within other frameworks, DOM elements may be reused, making it impossible for componentDidUnload() to be accurate 100% of the time if it is disconnected, then re-connected, and disconnected again. Instead, disconnectedCallback() is the preferred way to always know if a component was disconnected from the DOM.

**Comment by rwaskiewicz** [comment]
I'm going to close this out, since it hasn't seen any activity. If you feel the question hasn't been adequately answered please feel free to comment on this issue/open a new one. Thanks!
