### ISSUE TITLE
typo in the docs-md/advanced/angular-integration/index.md

### ISSUE THREAD

**Issue by hufan-akari** [ionic-team/stencil-site#103]
https://github.com/ionic-team/stencil-site/blob/2af659e8953fb0ae05b42bdc5c05e633f8973759/docs-md/advanced/angular-integration/index.md#L11

>  Including the CUSTOM_ELEMENTS_SCHEMA in the nodule allows the use of the web components in the HTML markup without the compiler producing errors. Here is an example of adding it to `AppModule`: 

Does the `nodule` mean to "module" ?

**Comment by pwespi** [comment]
Fixed in https://github.com/ionic-team/stencil-site/pull/105.

**Comment by jgw96** [comment]
Thanks for the PR!
