### ISSUE TITLE
Docs: Missing space in code comment for https://stenciljs.com/docs/reactive-data

### ISSUE THREAD

**Issue by mdstaff** [ionic-team/stencil-site#1042]
While reading the docs page for https://stenciljs.com/docs/reactive-data I noticed a likely typo.

I am going to create a PR to fix this issue momentarily per your contributing guidelines.

Screenshot showing typo:
<img width="671" alt="Screen Shot 2023-02-16 at 9 58 47 PM" src="https://user-images.githubusercontent.com/244685/219545991-5c55748a-d8a0-4b63-bfd5-d50d3c3ca0d9.png">

**Comment by rwaskiewicz** [comment]
Closing, as we just merged the PR. Thanks again!
