### ISSUE TITLE
The document home page has a bug

### ISSUE THREAD

**Issue by GuoJikun** [ionic-team/stencil-site#1055]
Click the button "npm init stencil" and the copied text is incorrect.

![image](https://user-images.githubusercontent.com/21582741/221745157-f27ceab2-7a93-4702-a503-30a9d134323c.png)

**Comment by rwaskiewicz** [comment]
Thanks @GuoJikun! I've given the web team a heads up!

**Comment by rwaskiewicz** [comment]
Closing this out - the web team fixed this this afternoon. Thanks again!
