### ISSUE TITLE
Can't access https://stenciljs.com/docs/compiler-config

### ISSUE THREAD

**Issue by PChiesa** [ionic-team/stencil-site#119]
Hi, an hour ago the link https://stenciljs.com/docs/compiler-config stopped working, it goes on loop.

**Comment by jgw96** [comment]
Thanks for opening an issue with us, looking into this.

**Comment by jgw96** [comment]
Fixed and deploying now (:

**Comment by PChiesa** [comment]
Thank you so much for the quick fix!

**Comment by jgw96** [comment]
No problem at all! Be sure to refresh to make sure you get the latest change, I had to change the url slightly. Oh and thanks for using Stencil!
