### ISSUE TITLE
Link to "constraint validation api" broken

### ISSUE THREAD

**Issue by bitflower** [ionic-team/stencil-site#120]
On this page: https://stenciljs.com/docs/forms/

Points to https://www.w3.org/TR/html5/forms.html#the-constraint-validation-api which gives a 404.

**Comment by jgw96** [comment]
Thanks for opening an issue with us! I just fixed this with https://github.com/ionic-team/stencil-site/commit/730fe29af242a740dfa58880ec31d8f6e2540099.
