### ISSUE TITLE
Missing content in styleUrls docs

### ISSUE THREAD

**Issue by anselmbradford** [ionic-team/stencil-site#1214]
1. Visit https://stenciljs.com/docs/component#styleurls
2. See garbled content in the details section:

```
Alternatively, an object can be provided that maps a named "mode" to one or more stylesheets. This

By out of the box, Stencil will only process CSS files (ending with .css). 
```

**Comment by rwaskiewicz** [comment]
Ah, good catch!

**Comment by rwaskiewicz** [comment]
Thanks @anselmbradford ! I've merged https://github.com/ionic-team/stencil-site/pull/1215, which is a quick fix for the time being. Longer term, we need to get some better documentation around style 'modes' in Stencil. Until we do that, I'm going to keep this issue open. Thanks again!
