### ISSUE TITLE
stenciljs website does not pass all of the lighthouse PWA checks

### ISSUE THREAD

**Issue by ajiteshr7** [ionic-team/stencil-site#124]
I guess from Chrome 64 onwards stenciljs website fails on few of the PWA checks.

**Comment by leebrandt** [comment]
seeing failing checks in Chrome 63.0.3239.132 as well.

**Comment by jgw96** [comment]
Hello all! I just updated the site a few days ago to pass more of the new checks and will be adding more updates to make sure were green on all the tests. Thanks!

**Comment by jgw96** [comment]
Closing this as recent deploys have improved this. Thanks for opening an issue with us!
