### ISSUE TITLE
Two links for Stencil Configuration Documentation

### ISSUE THREAD

**Issue by gringonivoli** [ionic-team/stencil-site#134]
One from menu (https://stenciljs.com/docs/config) and other from the "Next" button (https://stenciljs.com/docs/stencil-config) in the Testing page (https://stenciljs.com/docs/testing).

**Comment by jgw96** [comment]
Fixed with https://github.com/ionic-team/stencil-site/commit/801bcdc81fdf1bf4b98bfd1f0112b2152a33d99b
