### ISSUE TITLE
Docs: Getting Started - Required Dependencies

### ISSUE THREAD

**Issue by webonix** [ionic-team/stencil-site#141]
This is a useful page if this is the first time starting in the ionic dev environment and would be good to have for each project

https://capacitor.ionicframework.com/docs/getting-started/dependencies

Thank you.

**Comment by jgw96** [comment]
Thanks for the suggestion! Added this here https://github.com/ionic-team/stencil-site/commit/ac1e18ca268ead8b780a2da79fdc647b24941141
