### ISSUE TITLE
Request: recommended style guide page

### ISSUE THREAD

**Issue by splitinfinities** [ionic-team/stencil-site#147]
The style guide you've made here is fantastic for Ionic, but it has content that would really benefit teams who want to learn the best style to follow for Stencil, and to include that as a page on the site. 

https://github.com/ionic-team/stencil/blob/master/STYLE_GUIDE.md

**Comment by jgw96** [comment]
Added with https://github.com/ionic-team/stencil-site/commit/363326e86839ac5a18bd3f65b6831ade100b5130. Thanks!
