### ISSUE TITLE
Framework integration docs out of date

### ISSUE THREAD

**Issue by zagnut007** [ionic-team/stencil-site#1473]
The docs on this page: https://stenciljs.com/docs/react seem to be out of date with the current state of the react-ouput-target. None of the referenced options exist on the output target as of "@stencil/react-output-target": "^0.6.0"

Pulling from: https://github.com/ionic-team/stencil-site/blob/main/versioned_docs/version-v4.20/framework-integration/react.md

**Comment by christian-bromann** [comment]
Thanks for raising the issue. We just released a new version of the Stencil docs and they should now be available without having to select the `Next` version.
