### ISSUE TITLE
error on templating-jsx page

### ISSUE THREAD

**Issue by rramsey** [ionic-team/stencil-site#1484]
On the templating-jsx page of the docs I think there's an error on line 210:
````
<div class="todo-one">
    {this.todos.map((todo) => (
        <span>{ todo.taskName }</span>
    )}
</div>
````
To get the output I wanted, I needed to add a `return` inside the map:

````
<div class="todo-one">
    {this.todos.map((todo) => (
        return <span>{ todo.taskName }</span>
    )}
</div>
````

In my specific case, I have two stencil components, call them parent and child. Parent takes in an array of objects as a @Prop, iterates through the array passing each object to the child. My index.html is setup with a script function that uses document.querySelector() to set the value of the items to the array.
Index.html:
````
<custom-parent items=""></custom-parent>
<script type="text/javascript">
    document.querySelector('custom-parent').items=arrItems; // where arrItems is an array of objects I've defined in ts
</script>
````
In my parent.ts file i have:
````
@Prop({ reflect: true }) items: ArrItemsClass[] = [];
render() {
    return (
        <div class="items-one">
            {this.items.map((item) => (
                return <custom-child name={item.taskName}></custom-child>
            )}
        </div>
    }
}
````
I also tried `<span>{item.taskName}</span>` and a couple of other variations. It was only when I used a `return` that the children or span actually displayed.

This is `"@stencil/core": "^4.7.0"`.

**Comment by christian-bromann** [comment]
Thanks for raising the issue!

> To get the output I wanted, I needed to add a `return` inside the map:

This is not correct. You see the map callback is enclosed with parenthesis `(` and `)` instead of curly braces which means that its value is returned immediately.

Happy to answer further questions but will go ahead and close this issue.
