### ISSUE TITLE
Document "appload" event dispatched on window

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/stencil-site#155]
And a page can have many different stencil apps on it, so in the event’s detail there’s the namespace too.

**Comment by adamdbradley** [comment]
```
window.addEventListener('appload', (ev) => {
    console.log(ev.detail.namespace);
});
```

**Comment by itsravenous** [comment]
I got here after trying to use the `stencil_appload`  event documented on the [config extras](https://stenciljs.com/docs/config-extras#lifecycledomevents) page, which it appears was renamed and changed to "always on" in https://github.com/ionic-team/stencil/pull/2285/files

I've removed the outdated event in #705 , but I'll leave it to the Stencil team to decide where is best to document the new event.

If you got here trying to find out how to listen for the global event that Stencil emits when all components have loaded, this is how:

```js
window.addEventListener('appload', () => {
  // All component have now loaded
});
```

**Comment by claviska** [comment]
Added in 8048260313c3c8a761eab88b9cf4bd7e91af6d58
