### ISSUE TITLE
Document listeners

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/stencil-site#157]
As of `0.7.6`, Listeners can be added to specific elements within JSX.

For example, if a component emits the event `ionChange`, then the JSX attribute `onIonChange` can be added, such as:

```
<ion-input onIonChange={ev => this.someMethod(ev)}/> 
```

**Comment by adamdbradley** [comment]
https://github.com/ionic-team/stencil/blob/master/CHANGELOG.md#-076-2018-03-22

**Comment by jgw96** [comment]
Added with https://github.com/ionic-team/stencil-site/commit/37f5f4d0f74891b66ae371f81c94719d895bb357
