### ISSUE TITLE
Minor structure changes

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/stencil-site#16]
- [x]  in the left menu, call it "Basics" instead of "Component Basics"
- [x] Stencil configuration link should be moved to the Advanced section in the left menu
- [x] "Building Components" should be renamed to "Decorators"
- [x] think we need to improve how we list out the various Decorators and what they do
- [x] Learn JSX should probably be renamed to "Templating" or something
- [x] Rename "My First Stencil Component" to "My First Component"

**Comment by jgw96** [comment]
Closing this as it looks like that last one is already done https://stenciljs.com/docs/my-first-component
