### ISSUE TITLE
Recursive fetch keeps downloading things

### ISSUE THREAD

**Issue by zachleat** [ionic-team/stencil-site#169]
Using Firefox 59 on Mac OS (Low) Sierra

1. Go to https://stenciljs.com/docs/getting-started
2. Open the `stencil-router` in a new tab
3. It recursively requests the page contents

![image](https://user-images.githubusercontent.com/39355/38641369-68fb74b8-3d9c-11e8-81b0-f629028b7a6f.png)

![image](https://user-images.githubusercontent.com/39355/38641374-6e4a95ac-3d9c-11e8-9fcb-52dc799fdbdb.png)

**Comment by adamdbradley** [comment]
Ahh sorry about that, just did a fresh deploy and we're getting it fixed up.

**Comment by zachleat** [comment]
No worries! Thanks!

**Comment by zachleat** [comment]
Hmmm, I just retested this and it doesn’t endlessly loop but it does duplicate: 
<img width="313" alt="image" src="https://user-images.githubusercontent.com/39355/38884486-65f7dd40-4235-11e8-902e-2f3f9dc7f90d.png">

**Comment by jgw96** [comment]
@zachleat what URL are you on when this happens?

**Comment by zachleat** [comment]
Hmm, no not really just 
![image](https://user-images.githubusercontent.com/39355/38902406-fd85cdf4-4265-11e8-9d65-131f975ad2f4.png)

A ha! This is a better clue:
![image](https://user-images.githubusercontent.com/39355/38902437-1e36fa46-4266-11e8-8fda-05d8203aa3a8.png)

Looks like an undefined fetch is returning the index page
![image](https://user-images.githubusercontent.com/39355/38902439-2334beb6-4266-11e8-9b8b-f2cdea332d35.png)

**Comment by jgw96** [comment]
Yeah good find! I'm not sure why people have not run into this before, but this is gonna be a good fix

**Comment by jgw96** [comment]
Hello all! This issue has since been fixed. The fix was a service worker related issue that we solved in Stencil. Thanks for using Stencil everyone!

**Comment by zachleat** [comment]
LGTM!
