### ISSUE TITLE
Learn More Link Breaks Page in Chrome and Firefox

### ISSUE THREAD

**Issue by TheAlexPorter** [ionic-team/stencil-site#173]
Hi Team,

In Firefox, when you click the "Learn More" link from the home page, it loads the docs within the docs.

In Chrome, when you click the "Learn More" link from the home page, the docs page hangs with a white screen.

Both issues are fixed by refreshing the page. I've attached screenshots so you can see what I mean.

<img width="1406" alt="firefox inception bug" src="https://user-images.githubusercontent.com/9155454/39024015-6ff7ca7c-43fb-11e8-8bd2-b3f34c34573a.png">

![chrome bug](https://user-images.githubusercontent.com/9155454/39024030-82e9443a-43fb-11e8-947c-8943109123cf.png)

**Comment by jgw96** [comment]
Hello! This has since been fixed, thanks!
