### ISSUE TITLE
globalStyle section has many mistakes

### ISSUE THREAD

**Issue by dimi-nk** [ionic-team/stencil-site#189]
# Currently

### globalStyle
Stencil is traditionally used to compile many components into an app, and each component comes with its own compartmentalized styles. However, it's still common to have styles which should be "global" across all components and the website. A global CSS file is often useful to set CSS Variables.

Additonally, the globalStyle config is can be used to precompile styles with Sass, PostCss, etc.

Below is an example folder structure containing a webapp's global sass file, named app.scss.

```
  src/
    components/
    globals/
      app.css
```

The global style config takes an array of file paths. The output from this build will go to the buildDir. In this example it would be saved to www/build/app.css.

```
globalStyle: ['src/globals/app.scss']
```

Next, the app.css can be referenced from the index.html file, such as:

```
<link href="/build/app.css" rel="stylesheet">
```

# Problems

1. on the first code snippet, under `globals` the file is `app.css` instead of `app.scss`
2. `globalStyle` takes a string, not an array of strings (not sure if bug or documentation error)
3. the generated file is not `app.css` but `<namespace>.css` which is not obvious (looks like `app.scss` is simply renamed to `app.css`

**Comment by jgw96** [comment]
Hello! Thanks for using Stencil. I just pushed a commit to update this doc.
