### ISSUE TITLE
Update document.title

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/stencil-site#19]
`document.title` should update for each page. Probably need to investigate more the ideal way to do this.

**Comment by mhartington** [comment]
Probably quick and easy way of doing this is just to update the title with `PropsDidChange`

Though this probably is something that the router should take care of. 
How does react router or any other router handle this?

**Comment by jgw96** [comment]
Closing this as adam added it with https://github.com/ionic-team/stencil-site/commit/f12ee18ad1f67d303e74582fa38383f44442ee56
