### ISSUE TITLE
Website screen flash

### ISSUE THREAD

**Issue by peterennis** [ionic-team/stencil-site#191]
You man need to use something like this:

https://docs.angularjs.org/api/ng/directive/ngCloak

![stencil-flash](https://user-images.githubusercontent.com/140737/41813145-11687dd6-76e5-11e8-8480-46dc1e045239.gif)

**Comment by jgw96** [comment]
Hello! This has since been fixed. Because of this I am going to be closing this issue for now. Thanks!

**Comment by peterennis** [comment]
@jgw96 Please provide a link to the fix.
