### ISSUE TITLE
Correct components lifecycle comment

### ISSUE THREAD

**Issue by jfer-rubio** [ionic-team/stencil-site#193]
`componentDidUpdate` comment says `componentWillUpdate ...` instead.
I plan to send a PR if issue is valid.

![image](https://user-images.githubusercontent.com/2468428/42537406-635a6f3c-845a-11e8-9ed7-8329179ec1a5.png)

**Comment by rwaskiewicz** [comment]
Thanks! This appears to have been fixed by a previous iteration of the Stencil team. I apologize that no one responded to this at the time. I appreciate the call out to help make these docs better 💙
