### ISSUE TITLE
Incorrect file path in example

### ISSUE THREAD

**Issue by dboscanv** [ionic-team/stencil-site#200]
In the config section, in the example of how to apply global styles, the name of file is incorrect. Is a minor mistake, but maybe cause confusion in someone. 

https://stenciljs.com/docs/config/#globalStyle

Actually:
globalStyle: 'src/globals/app._scss_'

Should be:
globalStyle: 'src/globals/app.**css**'

**Comment by rwaskiewicz** [comment]
Thanks! This has since been fixed insofar as I can tell. I apologize it took so long on the team to respond to this issue. I appreciate you calling this out!
