### ISSUE TITLE
Tables are hard to read

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/stencil-site#202]
I think the tables could use some spacing or lines between rows/columns. It's hard to read them.

See: https://stenciljs.com/docs/config#outputTargets

<img width="777" alt="screen shot 2018-07-25 at 4 16 38 pm" src="https://user-images.githubusercontent.com/6577830/43225760-f00098fc-9027-11e8-9140-e7d06dbb6928.png">

@kevinports

**Comment by kevinports** [comment]
@brandyscarney Totally agree! I need to take another pass at the content styles.
