### ISSUE TITLE
Rebuild the Component Lifecycle page

### ISSUE THREAD

**Issue by loklaan** [ionic-team/stencil-site#209]
Hey folks!

Looks like the first code example on https://stenciljs.com/docs/component-lifecycle isn't being rendered as typescript.

![screen shot 2018-09-15 at 1 40 43 pm](https://user-images.githubusercontent.com/1560301/45582074-0d052100-b8ed-11e8-8063-0cc994e4ed2c.png)

This isn't an issue in the latest version of the site, as built locally, so it might be something to do with deployment caching?

Cheers. Cool project 👍

**Comment by arjunyel** [comment]
I believe this is fixed now https://stenciljs.com/docs/component-lifecycle

**Comment by loklaan** [comment]
You're right - great!
