### ISSUE TITLE
Trouble using the stencil-router on a production server

### ISSUE THREAD

**Issue by apiaget** [ionic-team/stencil-site#240]
Hello,

I used stencil-router in my Stencil app and encoutered difficulties to run my app on a production server (Apache 2).
I could find a solution with some help in the stencil-router repo (https://github.com/ionic-team/stencil-router/issues/74).

Assuming not to be the only one facing this difficulty, I submitted a pull request containing an extract of Apache 2 and Nginx configurations.

I didn't know if theses information suited better in the stencil-router wiki.

Thank you,

Axel

**Comment by rwaskiewicz** [comment]
Looks like this issue was never closed when the PR was merged. Thanks again!
