### ISSUE TITLE
Table does not render in "Decorators" page

### ISSUE THREAD

**Issue by danawoodman** [ionic-team/stencil-site#253]
https://stenciljs.com/docs/decorators

![](https://cl.ly/7b0e11a97dfe/Screen%20Shot%202018-11-16%20at%2011.53.53%20AM.png)

**Comment by rwaskiewicz** [comment]
Thanks! It looks like this issue has been resolved in https://stenciljs.com/docs/component. I apologize that this issue wasn't responded to at the time it was reported - I appreciate the effort to help make these docs better 💙
