### ISSUE TITLE
Browser Support has inconsistent information about Firefox support

### ISSUE THREAD

**Issue by agneym** [ionic-team/stencil-site#269]
Page: [Browser Support](https://stenciljs.com/docs/browser-support/)

Issue: While the graphics at the beginning of the page and the table at the bottom strongly indicate that Firefox has support for Custom Elements from Firefox 63+, the description reads:

> Custom Elements are natively supported in Chrome and Safari (including iOS!) and are coming to both Edge and Firefox. In fact, Firefox has native support behind a flag, indicating full native support is near.

which seems to be outdated.

**Comment by arjunyel** [comment]
https://github.com/ionic-team/stencil-site/pull/278

**Comment by bambii7** [comment]
Can this be closed? The above Pull request 278 is merged and addresses this.

**Comment by ibrokemycomputer** [comment]
Does anyone maintain this repo? This has been resolved.

Additionally, the information about Edge is now out of date as well with the release of Edge 79 (January 2020).
