### ISSUE TITLE
Conditional rendering not working as expected

### ISSUE THREAD

**Issue by matchatype** [ionic-team/stencil-site#273]
I have a simple component fetching cards and I'd like to render a spinner component while loading, so I set up my componentWillLoad method for fetching and update the loading status.

However, the spinner never gets rendered (hydrated). Moving the fetching and state update logic to componentDidLoad method does indeed fix the issue, but it's not clear to me why.

**Comment by rwaskiewicz** [comment]
Hey there @matchatype 👋 

I apologize that is took so long for a member of the Stencil team to respond to this issue. While this may no longer be a concern of yours, if you're willing/able/still running into this issue, I'd greatly appreciate if you opened [a new issue in the Stencil repo](https://github.com/ionic-team/stencil/issues/new/choose). If not, I totally understand! Thanks!
