### ISSUE TITLE
Add Prop context docs

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/stencil-site#28]
https://github.com/ionic-team/stencil/issues/75#issuecomment-325193646

**Comment by adamdbradley** [comment]
@Prop({context: 'isServer'})

**Comment by motss** [comment]
Any brief explanation of this ATM?

**Comment by adamdbradley** [comment]
There is a short list of variables that are globally available through Prop context that may be useful to developers both during runtime and for unit testing:

```
isClient
isPrerender
isServer
window
document
```

**Comment by jgw96** [comment]
Talked to Adam offline and we are going to hold off on documenting this for now.

**Comment by jgw96** [comment]
This was recently added https://stenciljs.com/docs/context

**Comment by Gafilipoie** [comment]
This page is blank: https://stenciljs.com/docs/context

**Comment by Karankang007** [comment]
This needs to be reopened, this link https://stenciljs.com/docs/context does not work anymore.

**Comment by trazek** [comment]
Yes this link is broken. Perhaps context isn't meant to be used anymore?
