### ISSUE TITLE
Add Prop connect docs

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/stencil-site#29]
@Prop({connect: 'ion-animation-controller'})

**Comment by jgw96** [comment]
Talked to Adam offline and we are going to hold off on documenting this for now as it may change in the nearish future with ES modules.

**Comment by juanmiguelbesada** [comment]
Hi!

Still trying to figure how connect works in stencil?

Any tip here please?

**Comment by rwaskiewicz** [comment]
Closing, as this API no longer applies
