### ISSUE TITLE
[Suggestion] Add new third-party components

### ISSUE THREAD

**Issue by ftonato** [ionic-team/stencil-site#310]
Hello,

I'm studying { stencil } 💘 and today I launched three simple components [alert-component, badge-component, progress-component].

I think would be interesting to add these components on [third-party components list](https://stenciljs.com/resources).

You can find my components on my [stenciljs-components](https://github.com/ftonato/stenciljs-components) repository.

Please let me know what you do think for I send my pull-request...

**Comment by claviska** [comment]
There's a [Resources page](https://stenciljs.com/resources) with a "3rd Party Components" section you can add these to. Feel free to submit a PR!
