### ISSUE TITLE
Routing related issue on the site

### ISSUE THREAD

**Issue by d2s** [ionic-team/stencil-site#35]
After pressing back button few times at the Stencil website, I ended up to the URL https://stenciljs.com/docs/building-components that looked nothing like the normal site. Apparently route was looping the same home page component again and again.

Screenshot shows what the page looked like in Firefox:
![screenshot from 2017-09-03 13-59-36 stenciljs com - odd routing problem issue](https://user-images.githubusercontent.com/135053/30002370-4096e488-90b0-11e7-9cc8-507d4bfea8dd.png)

Also tried to load the URL with the Chrome browser, and it kept loading indefinitely without the main page content becoming visible.

_Browser version:_
Firefox 55.0.2

**Comment by jgw96** [comment]
Hello @d2s , mind giving this another try? I cant reproduce with the latest version of the site

**Comment by d2s** [comment]
@jgw96 I tried it again (on a different computer).

- Firefox 55.0.3 (64-bit) shows the page URL https://stenciljs.com/docs/building-components as following (screenshot image from the browser).

![screen shot 2017-09-08 at 19 06 39 stencil site bug](https://user-images.githubusercontent.com/135053/30220814-a8b102e8-94c9-11e7-840d-c586bcf323cd.png)

- Both of the latest Chrome and Safari versions keeps loading the https://stenciljs.com/docs/building-components page URL, but do not show any page contents (besides of an expanding scrollbar on the right side of otherwise empty page).

I don't remember what page I was looking before the browser ended up to that URL, so it is kind of difficult to reproduce that part of the issue. What I know is that the mentioned URL causes looping of the content.

**Comment by jgw96** [comment]
Ahh, you're hitting a dead link there. I think you're looking for https://stenciljs.com/docs/my-first-component. I need to get firebase to purge those url's.

**Comment by janpio** [comment]
Same happens with any unkown URL I think: https://stenciljs.com/docs/foobar
