### ISSUE TITLE
Docs excludeSrc wrong regex

### ISSUE THREAD

**Issue by drdreo** [ionic-team/stencil-site#350]
I have encountered troubles with the excludeSrc, that it doesn't exclude folders from the bundle. 
Came out the default value mentioned in the docs is not correct and needs to be updated.
Current [docs](https://stenciljs.com/docs/config#excludesrc): `['/test/', '**/.spec.']`
Correct: ` ['**/test/**', '**/*.spec.*']`

**Comment by lufego** [comment]
did you manage to get this working? I've just opened https://github.com/ionic-team/stencil/issues/1843

**Comment by drdreo** [comment]
Yeah, as mentioned in my comment, use the correct regex, not the one from the docs.
