### ISSUE TITLE
Docs hierarchy

### ISSUE THREAD

**Issue by splitinfinities** [ionic-team/stencil-site#36]
Docs, as organized now, aren't the most communicative of all the features stencil offers. 

Here are a couple examples that happened to me during my first hit on coding a stencil project:

1. Coming into typescript, it was interesting to know that decorators will decorate the following method. On [the decorators page](https://stenciljs.com/docs/decorators), the lead in copy doesn't support the page - what decorators are. This is a perfect opportunity to explain at a high level what a decorator does to make stencil better than other web component options. 

2. All decorators would benefit from having their own page. This was a challenge to me, learning what each decorators goals were. Additionally, because there's no `decorator archive page` > `decorator single page` hierarchy, it was easy for me to gloss over the `@Element` decorator, especially since it has a low footprint compared to the other decorators and their documentation on the same page. 

3. Collections don't have documentation. Today, I began working on a seperate collection of components that I could import into my original project. The project needed a collections file, but I wasn't sure why that wasn't being generated. Documenting this would be super helpful. 

--

With that feedback being said, here's a proposed hierarchy - unsure where this fits into your roadmap (I wouldn't know where to place the other GH issues)

Home
└ What is Stencil (About)
└ Getting Started (arguably, "starting a new proj" could be on the home page)
└ Basics
◽└ Components
◽└ Lifecycle
◽└ Templating (here, detail using `@Element`)
◽└ Decorators
◽◽└ `@Component`
◽◽└ `@Prop`
◽◽└ `@PropWillChange`
◽◽└ `@PropDidChange`
◽◽└ `@State`
◽◽└ `@Method`
◽◽└ `@Element`
◽◽└ `@Event`
◽◽└ `@Listen`
└ Advanced
◽└ Configuration
◽└ Collections
◽└ Serverside Rendering
└ Add-ons
◽└ Router
◽└ Submit yours? (I have a couple I could submit, but I'd prefer to put them on webcomponents.org)

-- 

Thoughts?

**Comment by adamdbradley** [comment]
Love it. Also, we'll be updating the docs so the left menu expands the sub menus like when you're viewing "Decorators". Thanks

**Comment by splitinfinities** [comment]
Here's an updated sitemap! 

Home
└ Essentials
◽└ Introduction
◽└ Getting Started
◽◽└ Components
◽◽└ Apps
◽◽└ Capacitor
◽└ Browser Support
└ Getting Started (arguably, "starting a new proj" could be on the home page)
└ Basics
◽└ My First Component
◽└ Using JSX
◽└ Lifecycle Methods
◽◽└ componentWillMount
◽◽└ componentDidMount
◽◽└ componentWillUpdate
◽◽└ componentDidUpdate
◽◽└ componentDidUnload
◽└ Decorators
◽◽└ @Component
◽◽└ @Prop
◽◽└ @Watch
◽◽└ @State
◽◽└ @Method
◽◽└ @Element
◽└ Events
◽◽└ @Event
◽◽└ @Listen
◽└ Forms
◽└ Updating Arrays and Objects
◽└ Unit Testing (since you'll be doing puppeteer soon, perhaps this would benefit from being a high level page? Depending on what puppeteer would offer for better testing)
└ Advanced
◽└ Stencil Configuration
◽└ Prerendering
◽└ Server Side Rendering
◽└ Service Workers
◽└ Shadow DOM
◽└ Distribution
◽└ Framework Integration
◽└ CSS Variables
└ Add-ons
◽└ Router
◽└ Sass
◽└ PostCSS
└ Community
◽└ Slack
◽└ Twitter
◽└ GitHub

**Comment by mhartington** [comment]
Awesome! Will get this added!
