### ISSUE TITLE
Complete documentation for End-to-end testing

### ISSUE THREAD

**Issue by feerglas** [ionic-team/stencil-site#376]
I love puppeteer, and i really love the puppeteer-abstraction that you made inside stencil. I saw that you did use JSDoc for anything inside `stencil/src/testing/puppeteer/` directory. So it would be easy to extract this to a wiki page which is documenting all the nice methods and properties that you provide us.

**Comment by adamdbradley** [comment]
Thanks for the suggestion, we'll take a look.
