### ISSUE TITLE
Docs incorrect Watch decorator link in properties.md

### ISSUE THREAD

**Issue by keithcrooks** [ionic-team/stencil-site#377]
Hi,

The Watch decorator link on the properties docs page is incorrect. It is linking to `#watch` on the current page. I believe this should point to `reactive-data/#watch-decorator` so I will make the change and create a PR.

Thanks

**Comment by keithcrooks** [comment]
I have made the change and opened a PR: https://github.com/ionic-team/stencil-site/pull/378

Thanks

**Comment by adamdbradley** [comment]
Merged! Thanks
