### ISSUE TITLE
component docs dead link

### ISSUE THREAD

**Issue by obedm503** [ionic-team/stencil-site#39]
There is a dead link that leads to https://stenciljs.com/components from https://stenciljs.com/docs/getting-started under the Developing header
>When we save, we'll have our component updated with the new changes. To learn more about what's going on in this component, check out [component docs](https://stenciljs.com/components)

**Comment by jgw96** [comment]
Hey! Thanks for opening an issue with us. I just pushed a commit to fix this and will deploy it shortly.
