### ISSUE TITLE
What does componentDidUnload stands for?

### ISSUE THREAD

**Issue by nikbabchenko** [ionic-team/stencil-site#432]
Currently Docs missing  information about _componentDidUnload_ hook. 
https://stenciljs.com/docs/component-lifecycle

Would be great to add one. 
Could create PR to add one with following:

### componentDidUnload
 _Cleanup just before Stencil destroys the component. Best place to detach event handlers to avoid memory leaks._
_Called just before Stencil destroys the component._

**Comment by nikbabchenko** [comment]
Added PR https://github.com/ionic-team/stencil-site/pull/433

**Comment by adrm** [comment]
I was about to open this issue because I noticed that the componentDidUnload hook only appears on the lifecycle summary chart, but not on the text.

**Comment by tricki** [comment]
Use of `componentDidUnload()` is discuraged and it will eventually be removed, see #618
