### ISSUE TITLE
Please, provide docs/guides for stencil/redux

### ISSUE THREAD

**Issue by pyummm** [ionic-team/stencil-site#455]
stencil-site/src/docs/guides/redux.md 
thanks!

**Comment by mrbfrank** [comment]
+1 @pyummm The README.md for [stencil-redux](https://github.com/ionic-team/stencil-redux) might help you while we wait.

**Comment by rwaskiewicz** [comment]
I'm going to close this, as we announced ending support for Stencil Redux earlier this year. I apologize it took so long for someone to take so long to address this!
