### ISSUE TITLE
Possible typo in FAQ section

### ISSUE THREAD

**Issue by john-law** [ionic-team/stencil-site#485]
1) I'm guessing the sentence I copied below from the FAQ / _Why does Stencil allow components to be lazy loaded?_  has a typo on remove, and it should be written read/learn instead. Maybe it's just me reading this wrong.

> You can also **remove** more about lazy loading in How Lazy-Loading Web Components Work with Stencil.

2. A minor typo on the Components / Properties / Attribute Name at:

> Properties and component attributes are strongly connected but not **necesary** the same thing.

**Comment by rtpHarry** [comment]
This can be closed
