### ISSUE TITLE
The content does not match the images with the documents

### ISSUE THREAD

**Issue by motss** [ionic-team/stencil-site#5]
## Description

Content does not match what's in the images shown in [Learning JSX](https://stenciljs.com/docs/learning-jsx).

Not sure if the content is right or the images just aren't those supposed to be on the same page.
Please ensure images or the content are relevant such as there are no `p` tags in any of the images, comma in between `div`s and no comma is found in any of the images.

Please look into fixing the contents and/ or the images.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! I just fixed the last of this issue with https://github.com/ionic-team/stencil-site/commit/3c7e9a04d5a4f73efd6dfed39f6fb8abce8fed40
