### ISSUE TITLE
Missing documentation for State Tunnel

### ISSUE THREAD

**Issue by sammartinez** [ionic-team/stencil-site#502]
Hey guys, 

Was curious really when the State Tunnel [documentation](https://stenciljs.com/docs/stencil-state-tunnel) is gonna be available. I did find [this](https://github.com/ionic-team/stencil-state-tunnel/wiki/Getting-started) documentation, but seems to be slightly out of date so was curious if there was anything newer. Appreciate it ahead of time!

**Comment by rwaskiewicz** [comment]
Hey there! 

I'm really sorry that it took so long for someone on the team (including myself after mentioning this issue in #937) to respond. We're no longer supporting state tunnel as a part of our efforts to focus Stencil on component libraries. As such, I'm going to close this ticket. I apologize again, this is very much on myself for not following up over a month ago.
