### ISSUE TITLE
Demo of nested routing

### ISSUE THREAD

**Issue by gregorypratt** [ionic-team/stencil-site#51]
The following page highlights how easy it is to get routing working in a Stencil app: https://stenciljs.com/docs/routing/

However after reading the paragraph about nested routes/components:
>When navigating to /demos/rendering based on the above configuration, the demos-page component will be loaded with a child component fiber-demo. Nested routes/components just work.

I'm not sure I understand how this hangs together. Maybe a more details demo would be useful to see what a `demos-page`and `fiber-demo` child component living at `/demos/rendering` might look like?

Also what does `exact` do? 😄

**Comment by newtonmunene99** [comment]
I'm sorry to re-open this but I still don't quite understand how nested routes work. I mean say for example i had a component 'app-home' and url is '/home', In it I have a sidebar/sidenav with a few routes/components. How do i navigate to 'home/route1' or 'home/route2'. Do I need something like <ion-nav/> or Angular's <router-outlet/> for example.

**Comment by newtonmunene99** [comment]
I really think we should have a demo for this. If it's not too much to ask that is.

**Comment by SleepySheepy172** [comment]
Strongly agree that this needs more docs/examples, it's 2021 now and I'm still struggling to find any examples of nested routes.
And the ones I have found haven't worked.
