### ISSUE TITLE
"piercing selector" deprecated in Puppeteer

### ISSUE THREAD

**Issue by trazek** [ionic-team/stencil-site#512]
The documentation found here: https://stenciljs.com/docs/end-to-end-testing#find-an-element-in-the-shadow-dom is no longer correct. It seems per this issue: https://github.com/GoogleChrome/puppeteer/issues/858 you can no longer use the ">>>" selector to query within the shadowRoot as that selector is deprecated. However I was able to test elements within the shadowRoot just fine using the `newSpecPage` rather than the `newE2EPage`.  Using the `newSpecPage`, I was able to do the following:

`newpage.root.shadowRoot.querySelector(INSERT_SELECTOR_HERE);`

If this is confirmed, I'd be happy to submit a PR with the changes to the docs?

**Comment by stevenpetryk** [comment]
What works for me is the undocumented `pierce/` prefix as of Puppeteer 5.4.

```ts
const el = await page.find('pierce/.something-in-shadow-dom')
```

Was a lifesaver when I discovered it!

**Comment by redidizzy** [comment]
@stevenpetryk you're a lifesaver ! I think this should be documented somewhere though...
