### ISSUE TITLE
Pre-rendering stencil-site seems not working, is the codebase missing smth ?

### ISSUE THREAD

**Issue by cptflammin** [ionic-team/stencil-site#513]
Hi all,
  trying to make running stencil-site with prerender. Using
```
npm run build.ci
```
then uploading www content into Apache /web directory.
.htaccess is
```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.html [L]
```
Desactivating JS oin Chrome Developer Cmd+Shift+P then 'disable javascript'
leaves the page nearly blank (with footer with only © 2019 StencilJS. Released under MIT License)
[https://gyd.ch/blog/stencil-roadmap-fall-2019](https://gyd.ch/blog/stencil-roadmap-fall-2019)

prerender.config.ts
```
module.exports = {

};
```
stencil.config.ts
```
import { Config } from '@stencil/core';

export const config: Config = {
  outputTargets: [
    {
      type: 'www',
      baseUrl: 'https://gyd.ch',
      serviceWorker: {
        unregister: true
      }
    },
    {
      type: 'dist-hydrate-script',
    }
  ],
  globalStyle: 'src/global/style/app.css'
};

```

**Comment by mlynch** [comment]
Not possible to debug this with the given information. Closing
