### ISSUE TITLE
Docs: JavaScript integration docs.

### ISSUE THREAD

**Issue by joekrump** [ionic-team/stencil-site#516]
The path to import `applyPolyfills()` and `defineCustomElements` from appears to be incorrect in the docs.

## Reproduction Steps

Follow the documentation to import Stencil generated components and apply polyfills as outlined here: https://stenciljs.com/docs/javascript
```html
<script type="module">
    import { applyPolyfills, defineCustomElements } from 'https://unpkg.com/test-components/latest/dist/esm/es2017/test-components.define.js';
    applyPolyfills().then(() => {
      defineCustomElements(window);
    });
</script>
```

## Expected outcome
My components are defined on the `window` and I can use them in my `.html`.

## Actual Result
My components are not registered because no `*.define.js` file exists in `dist` let alone `dist/esm/es2017/`.

## Proposed Fix
The React integration documentation appears to have the correct path to import `definedCustomElements()` and `applyPolyfills()` from. The fix I used was to update the path used for my plain JavaScript integration to match this and things worked!

**Example**
```html
<script type="module">
    import { applyPolyfills, defineCustomElements } from 'https://unpkg.com/test-components/latest/dist/loader';
    applyPolyfills().then(() => {
      defineCustomElements(window);
    });
</script>
```

**Comment by joekrump** [comment]
I have a pull request with the proposed update here: https://github.com/ionic-team/stencil-site/pull/515 however, it is failing CI for a reason that seems unrelated. I could use some help figuring out what's causing the CI failure as the update that I've made to the `.md` file seems like it should result in these failures.

**Comment by rtpHarry** [comment]
this can be closed
