### ISSUE TITLE
Printing pages does not work well

### ISSUE THREAD

**Issue by nitmws** [ionic-team/stencil-site#562]
I wanted to print out pages of this site with the latest Chrome browser. But with the default settings the width of the column with the content is only about 25 characters wide - see attached PDF printout.
Only changing the print scaling to 60% helps a little bit, but still about half of the width of a paper is empty. The site needs  CSS for printing.
[Typed Components - Stencil_2020-01-27.pdf](https://github.com/ionic-team/stencil-site/files/4116217/Typed.Components.-.Stencil_2020-01-27.pdf)

**Comment by rwaskiewicz** [comment]
Hey @nitmws 👋 

I apologize that it took so long for someone on the team to get back to you. We deployed a new version of the doc site with an updated tech stack this morning. Printing should work as expected now 🎉
