### ISSUE TITLE
Join newsletter feature is broken

### ISSUE THREAD

**Issue by rtpHarry** [ionic-team/stencil-site#569]
Tried to join the newsletter at the [bottom of the homepage](https://stenciljs.com/) but nothing happens.

Looking in the console log shows this error:

![image](https://user-images.githubusercontent.com/1038062/74588057-5c271800-4ff1-11ea-8c74-244691737446.png)

**Comment by rtpHarry** [comment]
@adamdbradley giving this a nudge as im not sure how closely this repo is monitored. 

The site is still broken as of today; nobody can join the mailing list.

**Comment by rtpHarry** [comment]
@mlynch maybe you're interested? :) newsletter has been broken for over two months now...

**Comment by mlynch** [comment]
Thanks @rtpHarry. What browser are you on? Works fine in Chrome for me but not Firefox. Guessing your browser is blocking something.

**Comment by mlynch** [comment]
Made a fix that seems to do it so should be fixed in the next 24 hours. Thanks again!
