### ISSUE TITLE
Document Unit Testing with @stenci/core/testing

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/stencil-site#60]
`@stencil/core/testing` landed in `0.0.6-2`

https://github.com/ionic-team/ionic/blob/d3e79fb46267e375905dd493829eaa36d9c1dc36/packages/core/src/components/button/test/button.spec.ts

**Comment by peterennis** [comment]
Typo in title:
s/stenci/stencil

**Comment by jgw96** [comment]
Closed with https://github.com/ionic-team/stencil-site/pull/69
