### ISSUE TITLE
Docs: typo with many periods at the end of a sentence

### ISSUE THREAD

**Issue by kimulaco** [ionic-team/stencil-site#602]
Stencil CLI's `--no-open` description `window..` looked like a typo.

https://stenciljs.com/docs/cli

> --no-open
> By default the --serve command will open a browser window. Using the --no-open command will no automatically open a browser window..

Sorry if it was intentional.
If this was a typo I can create a Pull Request.

**Comment by simonhaenisch** [comment]
I wouldn't call it "many" but yeah it's a typo 😄
