### ISSUE TITLE
Testing documentation is ambiguous about upstream Jest configuration

### ISSUE THREAD

**Issue by viernullvier** [ionic-team/stencil-site#605]
Right now, the testing configuration page states that Jest can be configured through the `testing` config setting in `stencil.config.ts`. It's not obvious that this is the __only__ way to configure Jest, other methods mentioned in the Jest documentation like adding a `jest` key to `package.json` or creating a file named `jest.config.js` simply won't work.

Addressing this explicitly will potentially save other developers some time and frustration. I've created a PR that adds a hint to the testing configuration page: #604

**Comment by rwaskiewicz** [comment]
Closing, since https://github.com/ionic-team/stencil-site/pull/604 was merged
