### ISSUE TITLE
Docs Issue: Minor Typo with word - 'treeshakable'

### ISSUE THREAD

**Issue by mrsan22** [ionic-team/stencil-site#635]
Minor Typo with word `treeshakable` in `src/docs/output-targets/dist.md`

> However, the generated bundle is <strong>threeshakable</strong>, ensuring that only imported components will end up in the build.

I will create a PR for this.

**Comment by mrsan22** [comment]
Here is the [PR](https://github.com/ionic-team/stencil-site/pull/636)

**Comment by rwaskiewicz** [comment]
Looks like this PR was merged, closing this issue. Thanks again!
