### ISSUE TITLE
Documentation Bindings.md

### ISSUE THREAD

**Issue by stevenfowler16** [ionic-team/stencil-site#648]
Navigate to Docs -> Framework Integration-> Bindings

Bindings.md has a few spelling errors that don't necessarily inhibit the understanding of the sentence but would look better with a few changes.

`This output target will emit a native angular/react/vue library, just like your components were **originaly wroten** using any of these frameworks.`

originally and written are spelled incorrectly. 

PR #647

**Comment by claviska** [comment]
Merged in #647.
