### ISSUE TITLE
z-index issue when searching

### ISSUE THREAD

**Issue by mbulfair** [ionic-team/stencil-site#656]
Noticed this issue while doing a search and there was a code example in the same space.

![image](https://user-images.githubusercontent.com/5325543/87051639-d6894c00-c1cd-11ea-923f-108675c3c997.png)

MAC OS 10.15.5
Chrome Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by claviska** [comment]
Fixed in ed95ded7179ca6f6f4673515b5d34381e5ae2bfd
