### ISSUE TITLE
`<code>` within titles has wrong style

### ISSUE THREAD

**Issue by tricki** [ionic-team/stencil-site#657]
Instances of `<code>` withing a title (`<h*>`) look wrong, almost like superscript:

![image](https://user-images.githubusercontent.com/523154/87087442-631a2580-c233-11ea-9fcc-6b39c40ff45e.png)
Source: https://stenciljs.com/docs/distribution#import-the-dist-library-using-a-bundler

- Chrome 83.0.4103
- Windows 10

**Comment by rwaskiewicz** [comment]
Hey @tricki 👋 

We deployed a new version of the site that has an updated tech stack. This should no longer be an issue 🎉 
![Screenshot 2023-01-25 at 11 49 27 AM](https://user-images.githubusercontent.com/1930213/214626046-cf4fcdf8-cc3d-4e0b-bf7c-cbd0c26a8779.png)
