### ISSUE TITLE
Docs main section is too narrow

### ISSUE THREAD

**Issue by biirus** [ionic-team/stencil-site#666]
From my perspective, the main section with text is too narrow right now. Code blocks are hard to read and the navigation section has almost the same width as the main one.
<img width="1904" alt="Screen Shot 2020-07-27 at 18 41 44" src="https://user-images.githubusercontent.com/1442293/88564223-9fbf8c80-d03b-11ea-8cda-87a0457a4619.png">

PR: https://github.com/ionic-team/stencil-site/pull/667

**Comment by claviska** [comment]
I agree that the content section is a bit narrow. Awesome work!

Just a couple (personal) opinions on this PR:

- We lose some spacing between the sidebars and the main content area, which is making it feel a bit cramped. It's still very readable, but I'm wondering if the main content's width can be widened a bit so we get some of that whitespace back.

- The search icon is very close to the text now

Before:
![image](https://user-images.githubusercontent.com/55639/88569397-60c41380-d008-11ea-9b07-b81fbe8c82b6.png)

After:

![image](https://user-images.githubusercontent.com/55639/88569451-733e4d00-d008-11ea-9646-d43ebc625015.png)

**Comment by biirus** [comment]
Thank you for your feedback!
Safari and Chrome render the search input a bit differently: 

Safari
<img width="230" alt="Screen Shot 2020-07-27 at 22 02 38" src="https://user-images.githubusercontent.com/1442293/88581109-5b40ea80-d055-11ea-9e3d-314a1aa2f054.png">

Chrome
<img width="228" alt="Screen Shot 2020-07-27 at 22 02 57" src="https://user-images.githubusercontent.com/1442293/88581128-63008f00-d055-11ea-9f56-f730f5c561de.png">

Safari has a special `::-webkit-search-decoration` pseudo element inside of it. I'll make it a bit more consistent.

According to the reduced paddings - TBH I don't why the content width is restricted by `660px` wide even on the large screens...
I'll make some changes and it would be great to have a review =)

**Comment by biirus** [comment]
Well, the ionic team uses the shared styles and components to have a consistent look and feel across all applications. For instance, at ionicons.com it works really great: 

<img width="896" alt="Screen Shot 2020-07-27 at 22 38 54" src="https://user-images.githubusercontent.com/1442293/88584484-5894c400-d05a-11ea-8a0c-e04bf73fd664.png">


However, it doesn't have a sidebar and aside TOC. So, it takes only 2/3 of that space at steciljs.com:

<img width="950" alt="Screen Shot 2020-07-27 at 22 40 53" src="https://user-images.githubusercontent.com/1442293/88584562-7b26dd00-d05a-11ea-80d0-727ab3d09546.png">

Now I'm wondering if it's to change the width of the main `.ui-container`...

**Comment by abohannon** [comment]
Shame this was closed. For a docs site, the narrow width that cuts off code example is really tough to read.
