### ISSUE TITLE
Bindings section in Angular integration documentation has a recursive link

### ISSUE THREAD

**Issue by eric-bednarz-dev** [ionic-team/stencil-site#699]
URL: https://stenciljs.com/docs/angular#bindings

The first paragraph ends with a link that is supposed to provide information about "what the story is without the bindings", but references the same page.

NB: when searching for issues, I found this one with my keywords:

https://github.com/ionic-team/stencil-site/issues/648

PR merged 5 months ago, but still open.

**Comment by eric-bednarz-dev** [comment]
Looks like it might be copied over (or generate from the same source) from here:

https://github.com/ionic-team/stencil-ds-output-targets#angular

**Comment by claviska** [comment]
Fixed in #701
