### ISSUE TITLE
Partially wrong linking of Next button or missing buttons

### ISSUE THREAD

**Issue by dkundel** [ionic-team/stencil-site#71]
Hi everyone,

I was reading through the docs and I realized that the `Next` button on the [Component Life Cycle page](https://stenciljs.com/docs/component-lifecycle) links to the [Stencil Config page](https://stenciljs.com/docs/stencil-config) rather than [Forms](https://stenciljs.com/docs/forms). 

Additionally are the buttons `Next` and `Back` completely missing on the pages [Forms](https://stenciljs.com/docs/forms), [Updating Arrays and Objects](https://stenciljs.com/docs/handling-arrays) and [Unit Testing](https://stenciljs.com/docs/testing).

I'm happy to submit a PR to fix this.

Cheers,
Dominik

**Comment by jgw96** [comment]
Thanks for the PR, just merged it! 🍻

**Comment by dkundel** [comment]
No problem and thanks for the quick merge :)
