### ISSUE TITLE
Update copy config docs

### ISSUE THREAD

**Issue by Phhansen** [ionic-team/stencil-site#73]
After digging through some code answering a question on slack i figured the documentation regarding the copy configuration could do with a little more explanation.

I´ll be happy to make a PR adding a little more information regarding the structure and properties required.

**Comment by jgw96** [comment]
@Phhansen feel free to do a PR, were always completely open to contributions! (:

**Comment by jgw96** [comment]
Going to close this for now as the PR was merged. Thanks again @Phhansen !
