### ISSUE TITLE
can we replace prismjs with highlight.js?

### ISSUE THREAD

**Issue by anlexN** [ionic-team/stencil-site#730]
i am reviewing your `stencil-site` source code. prismjs is written by old syntax and can not be understand very good. `ionic-team` some other repo, such like `ionicons-site` use highlight.js.

**Comment by rwaskiewicz** [comment]
Hey @anlexN! We've just deployed a new version of the site that uses a tech stack that aligns better with the rest of the Ionic org. I'm going to close this as a result - thanks for the suggestion!
