### ISSUE TITLE
Docs: Update Vue integration to include @stencil-vue-output-target

### ISSUE THREAD

**Issue by bmpickford** [ionic-team/stencil-site#751]
Page Ref: https://stenciljs.com/docs/vue

### Description
Currently the documentation describes a manual integration into Vue. An [output target for Vue](https://github.com/ionic-team/stencil-ds-output-targets/tree/master/packages/vue-output-target) now exists so this could be added to the documentation

### Possible Solution
Update site docs to match https://github.com/ionic-team/stencil-ds-output-targets#vue

**Comment by rwaskiewicz** [comment]
This has been completed in #864 - thanks again!
