### ISSUE TITLE
Document dist-custom-elements output target

### ISSUE THREAD

**Issue by markacianfrani** [ionic-team/stencil-site#765]
**Stencil version:**
```
 @stencil/core@<any>
```

**I'm submitting a:**
[x] feature request

Provide documentation on the `dist-custom-elements` output target. This is a really useful feature that is undocumented. So far I've found it leads to a way smaller bundle size and provides a lighter weight option for users to cherry pick individual components. 

**Questions to consider:**
* How does this differ from `dist-custom-elements-bundle`? (the naming is definitely super confusing)
* What are some real world use cases? (looks like Ionic has an [experimental build](https://github.com/ionic-team/ionic-framework/tree/main/core#custom-elements-build-experimental) that's using it?)
* What are the trade offs? When shouldn't I use this? I'm guessing that each component imports some things from stencil core so it might be inefficient if you're cherry picking a bunch of components? 

**Additional considerations:**

Is `dist-custom-elements` supposed to used in the Vue output target? The [docs](https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/button/button.tsx) mentioned this:

```
customElementsDir
This is the directory where the custom elements are imported from when using the [Custom Elements Bundle](https://stenciljs.com/docs/custom-elements). Defaults to the components directory. Only applies when includeImportCustomElements is true.
```

the `components` directory is the default directory of the dist-custom-elements output target. which makes me think that it was meant for this target. Either way, it works flawlessly with it.

**Comment by splitinfinities** [comment]
This is complete! https://stenciljs.com/docs/custom-elements
