### ISSUE TITLE
Demo site for StencilJS points to repo

### ISSUE THREAD

**Issue by yejodido** [ionic-team/stencil-site#77]
Super tiny change; sorry I don't have the time at the moment to submit a PR.

https://github.com/ionic-team/stencil-site/blob/fa69b7d257f31beed05d51481f10161c475c9f11/src/components/demos-page/demos-page.tsx

`demos = [
    {
      title: 'Stenciljs.com',
      description: 'Yep, this site is also built with Stencil!',
      url: 'https://github.com/ionic-team/stencil-site',
      source: 'https://github.com/ionic-team/stencil-site',
    },
`

**Comment by adamdbradley** [comment]
Thanks! https://github.com/ionic-team/stencil-site/commit/3441f5d631edc13a57f12a6773bb5e8e018d8c6f
