### ISSUE TITLE
Angular Bindings Documentation incomplete

### ISSUE THREAD

**Issue by ChazUK** [ionic-team/stencil-site#783]
It appears that the Angular Bindings documentation is not complete and contains incorrect code. https://stenciljs.com/docs/angular#bindings

ValueAccessorConfig is not used, there's no example of angularValueAccessorBindings.

```
import { Config } from '@stencil/core';
import { angularOutputTarget, ValueAccessorConfig } from '@stencil/angular-output-target';

export const config: Config = {
  namespace: 'demo',
  outputTargets: [
    angularOutputTarget({
      componentCorePackage: 'component-library',
      directivesProxyFile: '../component-library-angular/src/directives/proxies.ts',
      valueAccessorConfigs: angularValueAccessorBindings,
    }),
    {
      type: 'dist',
    },
  ],
};
```

Is it possible to get an example repo where this is working correctly?

**Comment by splitinfinities** [comment]
Hey @ChazUK! We just put up some changes to this page. Thank you for the patience! 

https://stenciljs.com/docs/angular
