### ISSUE TITLE
Vue 3

### ISSUE THREAD

**Issue by xesjkeee** [ionic-team/stencil-site#799]
Hey, Stencil Team 👋 

Much thanks for your compiler!

I have only one question, how are things for support Vue 3?

**Comment by rwaskiewicz** [comment]
Stencil now supports Vue 3 for it's output targets - the documentation for which can be found at https://stenciljs.com/docs/vue.  I'm going to mark this as 'done', but folks running into problems should feel free to open a new issue either in this repo for docs questions, or in https://github.com/ionic-team/stencil-ds-output-targets for bugs/feature requests.
