### ISSUE TITLE
Add Component decorator host option docs

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/stencil-site#82]
Explain `host` option:

```
@Component({
  host: {
    theme: 'toggle',
    role: 'checkbox'
  }
)
```

**Comment by Hotell** [comment]
it would be also nice to update interface type definitions in core ;)

**Comment by Hotell** [comment]
Also only thing that works is `theme` should I [re-open the issue](https://github.com/ionic-team/stencil/issues/277) ?

![image](https://user-images.githubusercontent.com/1223799/32454350-ed083c42-c316-11e7-8fc0-e170ebdce0c1.png)

**Comment by adamdbradley** [comment]
Gah you're right! Yeah that should work.
