### ISSUE TITLE
MSIE guidance is incomplete

### ISSUE THREAD

**Issue by FirstVertex** [ionic-team/stencil-site#822]
Our app needs to support MSIE 11 and I discovered the Stencil guidance on it [here](https://stenciljs.com/docs/config-extras).

However, even after implementing that, we still had errors in our app.  Upon further research it became apparent that we needed additional polyfills in the calling application (an Angular SPA).

I discovered [@ungap/custom-elements](https://github.com/ungap/custom-elements), which ultimately solved the issue for us.

Recommend to augment the Stencil docs page with MSIE guidance to also inform the user that additional Polyfill is needed in calling app, such as https://github.com/ungap/custom-elements

**Comment by rwaskiewicz** [comment]
Hey @FirstVertex 👋 

Is there a specific error message & Stencil configuration you can provide us with? Stencil _should_ be able to provide the necessary polyfills with a little bit of configuration to support IE11.  If there's something missing though, we'd be happy to add it!

**Comment by rwaskiewicz** [comment]
I'm going to close this issue due to inactivity. If this continues to be an issue/something you feel that we can improve on in the docs, please feel free to open a new issue

**Comment by FirstVertex** [comment]
Our firm finally let go of MSIE, and we no longer need to support it.  So this became a non-issue.  Ok to close it.
Thanks!
