### ISSUE TITLE
Stencil's Slack "invite link is no longer active."

### ISSUE THREAD

**Issue by metasean** [ionic-team/stencil-site#83]
On https://stenciljs.com/ —and without already having a slack account for the stencil group— click the "Stencil Slack" link (lower-left corner).  The redirect page states, "This invite link is no longer active.  Please check with the person who shared it with you to see if there's a new link available."

When the correct link is identified, it needs to be updated in the site-menu component (should be around somewhere close to here - https://github.com/ionic-team/stencil-site/blob/master/src/components/site-menu/site-menu.tsx#L150).

**Comment by metasean** [comment]
Updated slack link [tweeted](https://twitter.com/stenciljs/status/927945084146016256) after I submitted this issue.

A [pull request](https://github.com/ionic-team/stencil-site/pull/86) with the updated link has now been made.

**Comment by jgw96** [comment]
Hey! Sorry, I did not see your PR and have already fixed this in the latest version of the site. Big thanks for your PR though and always feel free to contribute in the future!
