### ISSUE TITLE
Conflicting `manifest.json` `icons` requirements

### ISSUE THREAD

**Issue by metasean** [ionic-team/stencil-site#84]
I've loved the concept of Web Components, and really enjoyed working with Ionic before I started working with React.  _I was crazy stoked when I learned about Stencil!_ 

I'm starting to develop a new PWA app that will include a web extension (maybe "interact" or be partnered with" a web extension is more clear).  Since Stencil can build components that can be used in a PWA or other html document Stencil seems like an awesome fit, at just the right time.

So I spun up the Stencil template and made a new component.
But when I started to try to wrap the resulting www/index.html into a web component, I hit a snag.

Specifically:
- Stencil / Web Component `manifest.json` expects an **_array_** of `icons`:
```
"icons": [
    {
      "src": "assets/icon/icon.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ]
```
- WebExtensions' `manifest.json` expects an `icons` **_object_**:
```
  "icons": {
    "48": "icons/beasts-48.png",
    "96": "icons/beasts-96.png"
  },
```

During development of Stencil components, is there a way to specify alternative manifest.json files? For example, instead of a `www` directory being made and maintained, having `pwa` and `webext` directories made and maintained with their respective manifest files?

**Comment by jgw96** [comment]
Hey! Since this is more of a question than an issue with the site I would recommend joining the Stencil slack https://join.slack.com/t/stencil-worldwide/shared_invite/enQtMjYwNjg5NDMzODQwLTdiNWZiNDMyMWRjZTBiMjIzMGFlOTZiZWVkNDVjNzc2ZTI5MzI2Y2VjZDgwYjczMjU3NWIxMDYzMzI2ZjY3NjM and asking there. Thanks!

**Comment by metasean** [comment]
At the time I posted this, I couldn't join Slack (because of #83).

Once I could join Slack, [I actually did post this question to it](https://github.com/ionic-team/stencil-site/issues/83) but unfortunately still haven't gotten any response. :-(
