### ISSUE TITLE
Angular framework intergration docs feels incomplete

### ISSUE THREAD

**Issue by jstnjs** [ionic-team/stencil-site#851]
Hi there,

I'm having trouble following the Angular framework integration docs. 

When I publish my package in NPM with the export `export { DIRECTIVES } from './lib/stencil-generated';` in `public-api.ts` (in my Angular component library). I'll get the error `Module '"@j1sc2s/angular-web-components"' has no exported member 'MyComponent'.` when I import my package in a clean Angular CLI project.

However when I change the export to `export * from './lib/stencil-generated/components';` in `public-api.ts`. It gives a different error in my clean installed Angular CLI project. `Cannot declare 'MyComponent' in an NgModule as it's not a part of the current compilation.`

It feels like i'm doing something wrong or something is missing in the docs. `@j1sc2s/angular-web-components: 0.0.12` is the package I made, following the docs.

**Comment by sardapv** [comment]
You just need to export components from index.ts as well just like you did for modules.

Add entry for components in index.ts of generated angular output folder

**Comment by jstnjs** [comment]
I added `MyComponent` in `public-api.ts`.

This is my public-api.ts right now:
<img width="478" alt="image" src="https://user-images.githubusercontent.com/33153367/158015760-6b6357fa-d748-4abe-9a58-20c09d0a2ea2.png">

I still get the `Cannot declare 'MyComponent' in an NgModule as it's not a part of the current compilation.` error. I have my core package as a dependency. My core dependency is included and works.

**Comment by sardapv** [comment]
Did you export the component out of the module? It seems you have only declared not exported. Add components entry into exports array and declarations array

**Comment by jstnjs** [comment]
Yeah, I did https://github.com/jstnjs/stencil-monorepo/blob/main/my-first-project/src/app/app.module.ts. I got it working through a primary NgModule, but still no luck with just the component. Still getting the same error.

**Comment by sardapv** [comment]
It won't work with just component. You need to have a module. Also its better to have SCAM modules for treeshaking.

**Comment by jstnjs** [comment]
Got it. Thanks! Just to verify.. this is what you mean right? https://github.com/jstnjs/stencil-monorepo/commit/8eb3c889e47b089d6243579015277f965ba59cc5

**Comment by sardapv** [comment]
Yes correct!
