### ISSUE TITLE
setAssetPath lacks usage detail

### ISSUE THREAD

**Issue by prakashraman** [ionic-team/stencil-site#877]
I have a component which resolves an asset path using `getAssetPath`

```
<img src={getAssetPath("icon.png")}>

// /build/icon.png
```

However, in the application (vue2) which imported my library, when I render the component the image path is just `/icon.png`. 

I would like to change the assetPath in the application. I tried using `setAssetPath` however, it did not result in any change.

How exactly should I use getAssetPath & setAssetPath?

**Comment by rwaskiewicz** [comment]
I'm going to close this issue due to inactivity. If this continues to be an issue/something you feel that we can improve on in the docs, please feel free to open a new issue
