### ISSUE TITLE
Document config flag `hydratedFlag`

### ISSUE THREAD

**Issue by JMDidon** [ionic-team/stencil-site#882]
Hello 🙂

I recently had an issue with the `hydrated` class that gets added by Stencil to indicate a component is ready to be rendered. Long story short, I have a global `MutationObserver` that gets added by a 3rd party that I can't modify nor remove/replace, and having this class added for every component can be expensive in this scenarion.

Thanks to the community in Stencil's Slack channel I have eventually found the `hydratedFlag` in the config that covers my need. But I think this flag should be exposed in the documentation too for people that might need it.

I would be happy to propose a PR if it gets accepted!

**Comment by rwaskiewicz** [comment]
Hey @JMDidon, would be happy to accept a PR!
