### ISSUE TITLE
How to add Simplified Chinese version of the document

### ISSUE THREAD

**Issue by GuoJikun** [ionic-team/stencil-site#917]
I want to add Simplified Chinese version of the document, what should I do？

**Comment by alicewriteswrongs** [comment]
Hello, and thanks for you interest in translating the Stencil documentation! Unfortunately at present we don’t have a great infrastructure in place for hosting translated documentation. There is currently a separate site which hosts a Japanese translation, but the current Stencil documentation site architecture doesn’t facilitate multiple translations living side-by-side. We are currently working on migrating to Docusaurus, which has extensive support for various translation workflows, at which point we’ll be able to re-evaluate incorporating translated documentation into the main Stencil site.

**Comment by GuoJikun** [comment]
I'm looking forward to getting it done soon.

> Hello, and thanks for you interest in translating the Stencil documentation! Unfortunately at present we don’t have a great infrastructure in place for hosting translated documentation. There is currently a separate site which hosts a Japanese translation, but the current Stencil documentation site architecture doesn’t facilitate multiple translations living side-by-side. We are currently working on migrating to Docusaurus, which has extensive support for various translation workflows, at which point we’ll be able to re-evaluate incorporating translated documentation into the main Stencil site.

**Comment by GuoJikun** [comment]
Has the translation of simplified Chinese started?

**Comment by rwaskiewicz** [comment]
@GuoJikun Not yet, we're currently evaluating the best way to accept contributions from the community for translations like this

**Comment by GuoJikun** [comment]
> @GuoJikun Not yet, we're currently evaluating the best way to accept contributions from the community for translations like this

Do you have an evaluation?

**Comment by rwaskiewicz** [comment]
> Do you have an evaluation?

Not at this time, no.
