### ISSUE TITLE
Documentation for turborepo integration with stencilJS

### ISSUE THREAD

**Issue by MogLuiz** [ionic-team/stencil-site#923]
Turborepo is a monorepo building tool that was recently acquired by vercel.
It is a tool that is on the rise in the community and is already being used by large companies in the world such as: Netflix, AWS, Microsoft, Disney, Alibaba, Shopify, etc...
I think the StencilJS integration documentation with Turborepo is very important, with practical examples.

**Comment by rwaskiewicz** [comment]
Hey @MogLuiz 👋 

Is there anything in particular you're looking for? Is there something in the Turborepo documentation that isn't clear/that you're having issue with in Stencil?

Thanks!

**Comment by MogLuiz** [comment]
Hi @rwaskiewicz !

It's not a specific problem, I opened this issue due to the lack of content about the integration of these tools.
It's one more suggestion, because I think it will add a lot to the community.

**Comment by rwaskiewicz** [comment]
Gotcha! I'm going to label this to see if there's additional interest from the rest of the community for a Turborepo guide. If folks could 👍 the **summary in this issue** (please don't comment 👍) that'd be a big help!

**Comment by rwaskiewicz** [comment]
Hey there! After ~3 months, we unfortunately haven't had any additional requests for this type of content. As a result, I'm going to close this issue. However, we may re-evaluate turborepo-related documentation again in the future if there's another round of interest. Thanks!
