### ISSUE TITLE
Framework Integrations - Documentation needs update?

### ISSUE THREAD

**Issue by Matos55** [ionic-team/stencil-site#931]
Greetings,

I'm loving the stencil tool. Really makes the creation of web-components in a super-fast and friendly way.

Nonetheless, I and other people have tried to follow, thoroughly, the instructions in order to **build "framework wrappers"** for the web-components with stencil, to no avail.

https://stenciljs.com/docs/angular
https://stenciljs.com/docs/react

Can someone, please confirm, if the instructions provided are update to date? or if there is anything missing?

Thank you in advance!
Happy codding =)

**Comment by rwaskiewicz** [comment]
Hey @Matos55 👋 

The instructions _should_ be up to date. If you can provide us with the error message and an example repository, we can see if there's anything we can improve on in the docs. Thanks!

**Comment by kensodemann** [comment]
@Matos55 

In addition to the docs, I have [created a repo](https://github.com/ionic-enterprise/cs-demo-weather-widgets) that contains notes on setting everything up.

It is a simple PNPM based monorepo and each of the [packages](https://github.com/ionic-enterprise/cs-demo-weather-widgets/tree/main/packages) contains a NOTES.md file that highlights the important bits of information / clarification I found while following the official instructions. Feel free to have a look at that and see if it help you out.

As Ryan noted, though, any help you can give the help us improve the docs would be very much appreciated.

**Comment by Matos55** [comment]
> Hey @Matos55 👋
> 
> The instructions _should_ be up to date. If you can provide us with the error message and an example repository, we can see if there's anything we can improve on in the docs. Thanks!

Thanks for the fast reply.

I will create a repo and follow the instructions again with commits between.

**Comment by Matos55** [comment]
> @Matos55
> 
> In addition to the docs, I have [created a repo](https://github.com/ionic-enterprise/cs-demo-weather-widgets) that contains notes on setting everything up.
> 
> It is a simple PNPM based monorepo and each of the [packages](https://github.com/ionic-enterprise/cs-demo-weather-widgets/tree/main/packages) contains a NOTES.md file that highlights the important bits of information / clarification I found while following the official instructions. Feel free to have a look at that and see if it help you out.
> 
> As Ryan noted, though, any help you can give the help us improve the docs would be very much appreciated.

@kensodemann , will check it out, later on. 
Thanks for the repo =)

**Comment by Matos55** [comment]
@rwaskiewicz , please find below a public repo, where i've tested the instructions at:
[https://stenciljs.com/docs/angular](https://stenciljs.com/docs/angular)

[https://github.com/Matos55/stencil-webc](https://github.com/Matos55/stencil-webc)

Each commit belongs to each step.
Once again, thanks for all the support.

**Comment by rwaskiewicz** [comment]
Hey @Matos55 👋 

We've gone and rewritten our framework integrations docs for Angular, React and Vue to include better steps for consuming the wrapped angular component in an angular app. Please let us know if you have any questions!

**Comment by Matos55** [comment]
Hallo, @rwaskiewicz ,

Awesome news!

The new documentation is crystal clear.
Everything is now working as intended.

Thank you all so much =)
