### ISSUE TITLE
Youtube guide to use stencil with React and Angular doesn't work

### ISSUE THREAD

**Issue by squidjam** [ionic-team/stencil-site#962]
The video presented in https://www.youtube.com/watch?v=p9NaM4_CdmQ shows a series of commands that may have worked before but it seems like it's not up to date anymore, so it's not working.

Can you please remove it or replace it? It's most likely working against Stencil.
If this is not the correct place to ask for this, please (before deleting or closing it) pass it forward through the right channel?

Thanks.

**Comment by rwaskiewicz** [comment]
Hey @squidjam 👋 

Thanks for pointing this out! Can you confirm for me which commands you saw that weren't up to date? I saw a few myself, but wanted to make sure you and I are on the same page here.

**Comment by squidjam** [comment]
From the start, npx create-nx-workspace doesn't ask for the workspace name anymore at the beginning.
So the option that one gets is "Choose what to create" and "core" is not in the options.
Choosing "integrated" will still not show you core.
One would have to use the core preset from the CLI.
From then on one can follow the video except that around 1:57 or so, a command is given that (maybe due to video encoding issues) is not visible.
We select CSS and then we get an error, a different one, that we need to install @nrwl/storybook
We do so and then get stuck with an error:
 `>  NX   (0 , devkit_1.updateNxJson) is not a function` 
 I pass verbose and we get:
 
```
TypeError: (0 , devkit_1.updateNxJson) is not a function
    at addTestInputs (C:\Projects\test-stencil\node_modules\@nrwl\jest\src\generators\init\init.js:100:31)
    at createJestConfig (C:\Projects\test-stencil\node_modules\@nrwl\jest\src\generators\init\init.js:36:9)
    at jestInitGenerator (C:\Projects\test-stencil\node_modules\@nrwl\jest\src\generators\init\init.js:145:5)
    at C:\Projects\test-stencil\node_modules\@nxext\stencil\src\generators\init\lib\add-jest.js:12:45
    at Generator.next (<anonymous>)
    at C:\Projects\test-stencil\node_modules\tslib\tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Projects\test-stencil\node_modules\tslib\tslib.js:114:16)
    at addJest (C:\Projects\test-stencil\node_modules\@nxext\stencil\src\generators\init\lib\add-jest.js:7:20)
    at C:\Projects\test-stencil\node_modules\@nxext\stencil\src\generators\init\init.js:19:59
```


For which I find no way to continue further...

**Comment by squidjam** [comment]
Sorry, the previous comment should have started with: "Hi, thanks for taking a look at this", but it seems I somehow managed to copy the whole thing without the greeting...

**Comment by rwaskiewicz** [comment]
Thanks! I've passed this on to our DevRel team to take a look/make a final decision here. I'll circle back and update this issue when I hear back!

**Comment by rwaskiewicz** [comment]
We've decided to add a disclaimer to the blog that houses this video stating that the video uses an older version of nx and stencil, and the content may be out of date. Thanks again!

**Comment by squidjam** [comment]
Any plans to make a new video, though? Thanks.

**Comment by rwaskiewicz** [comment]
We don't have any immediate plans (to the best of my knowledge). But it's always a possibility 🙂
