### ISSUE TITLE
Typos and spelling issues in documentation

### ISSUE THREAD

**Issue by lcrespom** [ionic-team/stencil-site#98]
### In page https://stenciljs.com/docs/my-first-component
- In the last paragraph it says: "Any property decorated with @Props() ...", but the `@Props` decorator does not exist. It should say "Any property decorated with @Prop() ...".
- Also in the last paragraph, it says: "our component would fire **it's** render function again". It should say "our component would fire **its** render function again".
    - "It's" is a contraction of "it is", whereas "its" indicates posession.

### In page https://stenciljs.com/docs/forms
- At the end of the first section, it says "**Lets** go over what is happening here". It should say "**Let's** go over what is happening here".
    - "Lets" is the third person singular of "Let", as in "he lets you do it", whereas "Let's" is a contraction of "Let us".
- I did a search for "lets" and found two other places where it is misspelled:
    - docs-md/advanced/service-worker/index.md: "**Lets** go through the steps..."
    - docs-md/addons/stencil-router.md: "Now **lets** go over how..."

**Comment by jgw96** [comment]
Thanks for finding these! 😃  Would you be interested in doing a PR for this?

**Comment by lcrespom** [comment]
Sure, will do :-)

**Comment by jgw96** [comment]
Awesome, let me know if you need any help!

**Comment by lcrespom** [comment]
Already sent the PR

**Comment by jgw96** [comment]
Thanks for the PR @lcrespom !
